# commands:

# vanilla implementations
# if there is no 'enabled:' option, then the command has not been implemented yet
# the permission:"" tag is read only - changing it does nothing
advancement:
attribute:
ban:
  list:
ban-ip:
  list:
banlist:
bossbar:
clear:
  enabled: true
  permission: 'command.clear'
clone:
damage:
data:
datapack:
debug:
defaultgamemode:
deop:
difficulty:
effect:
enchant:
execute:
experience:
fill:
fillbiome:
forceload:
function:
gamemode:
  enabled: false
  permission: 'command.gamemode'
gamerule:
give:
help:
item:
jfr:
kick:
kill:
list:
locate:
loot:
me:
msg:
op:
pardon:
pardon-ip:
particle:
perf:
place:
playsound:
random:
recipe:
reload:
return:
ride:
rotate:
save-all:
save-off:
save-on:
say:
schedule:
scoreboard:
seed:
setblock:
setidletimeout:
setworldspawn:
spawnpoint:
spectate:
spreadplayers:
stop:
stopsound:
summon:
tag:
team:
teammsg:
teleport:
  enabled: true
  permission: 'command.teleport'
tell:
tellraw:
tick:
time:
title:
transfer:
trigger:
w:
weather:
whitelist:
worldborder:

testcommand:
  enabled: true
